// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Api.Data;

#nullable disable

namespace Portfolio.Api.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20251120222258_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Shared.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiveDemoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GitHubUrl = "https://github.com/tu-usuario/focus-flow",
                            LiveDemoUrl = "https://focusflow.azurewebsites.net",
                            ShortDescription = "Aplicación completa de gestión de tareas con prioridades y notificaciones.",
                            Technologies = "[]",
                            Title = "Sistema de Gestión de Tareas (FocusFlow)"
                        },
                        new
                        {
                            Id = 2,
                            GitHubUrl = "https://github.com/tu-usuario/catalog-api",
                            LiveDemoUrl = "",
                            ShortDescription = "Microservicio para manejar el inventario y catálogo usando NoSQL.",
                            Technologies = "[]",
                            Title = "API de Catálogo de Productos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
